/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Controller.Allfacturas;
import Controller.Cliente;
import Controller.Detalle;
import Controller.Factura;
import Controller.consultas;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class FacturasC extends javax.swing.JFrame {

    /**
     * Creates new form FacturasC
     */
    public FacturasC() {
        initComponents();
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla2.getTableHeader().setReorderingAllowed(false);
       // tabla3.getTableHeader().setReorderingAllowed(false);
        panel.setVisible(false);
        panel3.setVisible(false);
        panelbroswe.setVisible(false);
        text2.setVisible(false); 
        text1.setVisible(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id_cliente = new javax.swing.JTextField();
        browse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        text1 = new javax.swing.JLabel();
        txtidcliente = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        panel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla4 = new javax.swing.JTable();
        panelbroswe = new javax.swing.JPanel();
        id_factura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        broswe2 = new javax.swing.JButton();
        text2 = new javax.swing.JLabel();
        txtfactura = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Ingresa Id de cliente");

        browse.setText("Buscar");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre", "Correo", "Num cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        tabla2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabla2.setForeground(new java.awt.Color(102, 102, 102));
        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Facturación", "Fecha Facturación", "RFC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla2.setGridColor(new java.awt.Color(153, 153, 153));
        tabla2.setSelectionBackground(new java.awt.Color(153, 255, 153));
        jScrollPane2.setViewportView(tabla2);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        text1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 204, 0));
        text1.setText("Facutras del cliente:");

        txtidcliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod Producto", "Categoria", "Nombre producto", "Precio", "Cantidad", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla3);

        tabla4.setBorder(new javax.swing.border.MatteBorder(null));
        tabla4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabla4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Subtotal", null},
                {"Descuento", null},
                {"IVA", null},
                {"TOTAL NETO", null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabla4);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Buscar Factura:");

        broswe2.setText("Buscar");
        broswe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broswe2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelbrosweLayout = new javax.swing.GroupLayout(panelbroswe);
        panelbroswe.setLayout(panelbrosweLayout);
        panelbrosweLayout.setHorizontalGroup(
            panelbrosweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbrosweLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(id_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(broswe2)
                .addContainerGap())
        );
        panelbrosweLayout.setVerticalGroup(
            panelbrosweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbrosweLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelbrosweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelbrosweLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(panelbrosweLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelbrosweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(broswe2))))
                .addContainerGap())
        );

        text2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 204, 0));
        text2.setText("Detalles Factura:");

        txtfactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Users\\Asus\\Documents\\NetBeansProjects\\Prueba12\\src\\fondo\\2.png")); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(text2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(panelbroswe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(browse)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browse))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtidcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(panelbroswe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text2)
                    .addComponent(txtfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        try{
            DefaultTableModel modelo = (DefaultTableModel) tabla2.getModel();
            modelo.setRowCount(0);//Limpiar la tabla
           
            consultas consultas = new consultas();
            Cliente cliente = new Cliente();
             
            //manda el valor que escribimos y lo convierte a int
            cliente = consultas.getCliente(Integer.parseInt(id_cliente.getText())); 
            if(cliente.isExiste()){ //is existe : variable bool de la clase factura para saber si existe
                // Valores que se le asignan a la tabla con el resiltado del objeto
                tabla.setValueAt (cliente.getNombre() + " " + cliente.getAppat() + " " + cliente.getApmat(), 0, 0);
                tabla.setValueAt (cliente.getCorreo(), 0, 1);
                tabla.setValueAt (cliente.getId_cliente(), 0, 2);
          
                /**ACABA LA PRIMER TABLA**/      
                ArrayList<Allfacturas> facturas_cliente = new ArrayList<>(); 
                //se iguala a un metodo de consultas que retonrna un arraylist de allfacturas
              
                facturas_cliente = consultas.getAllFacturas(cliente.getId_cliente()); 
 
                 if(facturas_cliente.isEmpty()){
                    JOptionPane.showMessageDialog(null, "No tiene facturas");
                    panel.setVisible(false);
                    panelbroswe.setVisible(false);
                    text1.setVisible(false);
                    txtidcliente.setText("");
                }else{
                    text1.setVisible(true);
                    txtidcliente.setText("" + cliente.getId_cliente()); //lo convierte a string le idcliente
                    panel.setVisible(true);
                    panelbroswe.setVisible(true);
                    Object [] fila = new Object[3]; 
                    for(Allfacturas e:facturas_cliente){ //for each tipo de dato, variable: arraylist name
                        fila[0] = e.getId_factura();
                        fila[1] = e.getFecha_factura();
                        fila[2] = e.getRFC();
                        modelo.addRow(fila); //Recorre arraylist y añade lo que encuentra 
                       //tabla2.addRowSelectionInterval(1, 2);
                    }
                 }  
             
                
                //el objeto se crea para agregar a la tabla 
                
                
                /*FIN DE SEGUNDA TABLA**/
             
                
               /* panel3.setVisible(true);
                text2.setVisible(true); 
                txtfactura.setText(""+id_factura.getText());
                ArrayList<Detalle> detalles = new ArrayList<>();
                //arraylist que se iguala a un metodo de consultas y el parametro es idfactura
                detalles = consultas.getDetalles(Integer.parseInt(id_factura.getText())); 
                 Object [] fila2 = new Object[6]; 
                for(Detalle e:detalles){
                    fila2[0] = e.getId_producto(); 
                    fila2[1] = e.getCategoria(); 
                    fila2[2] = e.getProducto();
                    fila2[3] = "$"+e.getPrecio();
                    fila2[4] = e.getCantidad();
                    fila2[5] = "$"+e.getImporte();
                    modelo2.addRow(fila2);//agrega como fila cada que itera
                   //tabla2.addRowSelectionInterval(1, 2);
                }*/
                //tabla4.setValueAt ("$"+facturacion.getSubtotal(), 0, 1);
                //tabla4.setValueAt ("$"+facturacion.getDescuento(), 1, 1);
                //tabla4.setValueAt ("$"+facturacion.getIVA(), 2, 1);
                //tabla4.setValueAt ("$"+facturacion.getTOTAL(), 3, 1);
            }else{
                tabla.setValueAt ("" , 0, 0);
                tabla.setValueAt ("", 0, 1);
                tabla.setValueAt ("", 0, 2);
                tabla.setValueAt ("", 0, 3);
                tabla.setValueAt ("", 0, 4);
                tabla.setValueAt ("", 0, 5);
                panel.setVisible(false);
              
                JOptionPane.showMessageDialog(null, "No existe cliente con ese código");
            }
            
        }catch(Exception e){
            System.out.println(e.getMessage());
            tabla.setValueAt ("" , 0, 0);
                tabla.setValueAt ("", 0, 1);
                tabla.setValueAt ("", 0, 2);
                panel.setVisible(false);
                panelbroswe.setVisible(false);
                text1.setVisible(false);
                txtidcliente.setText("");
                panel3.setVisible(false);
                text2.setVisible(false); 
                txtfactura.setVisible(false); 
                
          
            JOptionPane.showMessageDialog(null, "No existe cliente con ese código o no tiene facturas");
        }
    }//GEN-LAST:event_browseActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        inicio inicio= new inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void broswe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broswe2ActionPerformed
         DefaultTableModel modelo2 = (DefaultTableModel) tabla3.getModel();
         modelo2.setRowCount(0);//Limpiar la tabla
        Factura facturacion = new Factura();
        facturacion = consultas.getFactura(Integer.parseInt(id_factura.getText())); 
            if(facturacion.isExiste()){
                panel3.setVisible(true);
                text2.setVisible(true); 
                txtfactura.setText(""+id_factura.getText());
                ArrayList<Detalle> detalles = new ArrayList<>();
                //arraylist que se iguala a un metodo de consultas y el parametro es idfactura
                detalles = consultas.getDetalles(Integer.parseInt(id_factura.getText())); 
                 Object [] fila2 = new Object[6]; 
                for(Detalle e:detalles){
                    fila2[0] = e.getId_producto(); 
                    fila2[1] = e.getCategoria(); 
                    fila2[2] = e.getProducto();
                    fila2[3] = "$"+e.getPrecio();
                    fila2[4] = e.getCantidad();
                    fila2[5] = "$"+e.getImporte();
                    modelo2.addRow(fila2);//agrega como fila cada que itera
                 
                }
                tabla4.setValueAt ("$"+facturacion.getSubtotal(), 0, 1);
                tabla4.setValueAt ("$"+facturacion.getDescuento(), 1, 1);
                tabla4.setValueAt ("$"+facturacion.getIVA(), 2, 1);
                tabla4.setValueAt ("$"+facturacion.getTOTAL(), 3, 1);
            }else{
                //panel.setVisible(false);
                panel3.setVisible(false);
                text2.setVisible(false); 
                txtfactura.setVisible(false); 
                //numfact.setText("");
                //numclient.setText("");
                JOptionPane.showMessageDialog(null, "No existe factura con ese código");
            }
    }//GEN-LAST:event_broswe2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturasC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturasC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturasC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturasC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturasC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar;
    private javax.swing.JButton broswe2;
    private javax.swing.JButton browse;
    private javax.swing.JTextField id_cliente;
    private javax.swing.JTextField id_factura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panelbroswe;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla2;
    private javax.swing.JTable tabla3;
    private javax.swing.JTable tabla4;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel txtfactura;
    private javax.swing.JLabel txtidcliente;
    // End of variables declaration//GEN-END:variables
}
